sudo: required
services:
  - docker

before_install:
  - docker build -t jeffthomson5150/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jeffthomson5150/react-test npm test

after_success:
  - docker build -t jeffthomson5150/multi-client ./client
  - docker build -t jeffthomson5150/multi-nginx ./nginx
  - docker build -t jeffthomson5150/multi-server ./server
  - docker build -t jeffthomson5150/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push jeffthomson5150/multi-client
  - docker push jeffthomson5150/multi-nginx
  - docker push jeffthomson5150/multi-server
  - docker push jeffthomson5150/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-852724245640
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
